/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: atomle (https://sketchfab.com/atomle)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/apple-watch-series-5-16950208bdf041f193c31d3b4a0ac15a
title: Apple watch series 5
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/appleseris5.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={5.34}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.12}>
          <mesh geometry={nodes.NIYNwKgmPYCkzpx.geometry} material={materials.RfziScXwNjFOjTf} />
          <mesh geometry={nodes.BrmhLaxyDmhbhXA.geometry} material={materials.KwQHVIjAaOBvYOl} />
          <mesh geometry={nodes.tqQTKXmBvXiXuUi.geometry} material={materials.iDKPrezlRKAMsXJ} />
          <mesh geometry={nodes.yTjoxDvwbAPZygY.geometry} material={materials.QGhrBgCXrJDNcrC} />
          <mesh geometry={nodes.yHafeexXAiPytbW.geometry} material={materials.FqtwwTANGDActcI} />
          <mesh geometry={nodes.KeqqEyvZchDDdlP.geometry} material={materials.AjFlTFrWzhywymA} />
          <mesh geometry={nodes.skbFGMQxPawHdOT.geometry} material={nodes.skbFGMQxPawHdOT.material} />
          <mesh geometry={nodes.ErOVeLWOcyHrdoT.geometry} material={nodes.ErOVeLWOcyHrdoT.material} />
          <mesh geometry={nodes.ajDgJcjsZTQAtOL.geometry} material={materials.rcZoXGfqfnZjYLv} />
          <mesh geometry={nodes.wflxnmxxYXvnLxp.geometry} material={materials.YRNmAgRITIuwDMU} />
          <mesh geometry={nodes.ePnvfhsUgYTHLdP.geometry} material={materials.iVwMRUBqdpoOFmg} />
          <mesh geometry={nodes.aynleugQGbyNYsa.geometry} material={materials.kFNgmsjtRAxVPtH} />
          <mesh geometry={nodes.HyRzdvVQMwELnwT.geometry} material={materials.upTfEpgNFxflqtf} />
          <mesh geometry={nodes.bvsBShDTmaTjbXM.geometry} material={materials.YpOtGMmrQbktABJ} />
          <mesh geometry={nodes.lnDzpNAJfMDjFms.geometry} material={materials.qxhxiJVpuwSrYLW} />
          <mesh geometry={nodes.lrTNGAQkeHccJph.geometry} material={materials.ycVxkCIsnetKUsw} />
          <mesh geometry={nodes.jChLaKiiqDISJhc.geometry} material={materials.sSZvqgMuWCuMkAr} />
          <mesh geometry={nodes.DzgfJtxUfpgExsF.geometry} material={materials.mUXcyUQCxEEJdiO} />
          <mesh geometry={nodes.MBrZKZXWsvHIcZQ.geometry} material={materials.JBuGosClPcYrSry} />
          <mesh geometry={nodes.acJwQeGdNxQWEyd.geometry} material={materials.OEDmdMOTgdNMXOP} />
          <mesh geometry={nodes.mcMtSAOyQxOEEfl.geometry} material={materials.sJrbBWzziZrNyXB} />
          <mesh geometry={nodes.qbgXzfcPGFYiUnN.geometry} material={materials.FBAtOQrXrgOoPNd} />
          <mesh geometry={nodes.dXSXlyOaLTQHAnn.geometry} material={materials.gMZhwegVXLXWOLd} />
          <mesh geometry={nodes.QpBpNnkHikCzRXn.geometry} material={nodes.QpBpNnkHikCzRXn.material} />
          <mesh geometry={nodes.JcqbcJEVwcScYbo.geometry} material={nodes.JcqbcJEVwcScYbo.material} />
          <mesh geometry={nodes.ToJTXgljlhhqitR.geometry} material={nodes.ToJTXgljlhhqitR.material} />
          <mesh geometry={nodes.MKkqtRcjcYdQNza.geometry} material={nodes.MKkqtRcjcYdQNza.material} />
          <mesh geometry={nodes.fWLGcfnLpXnhehz.geometry} material={materials.GdUNwQJEkZeKMrn} />
          <mesh geometry={nodes.aEQvkfzeWvwzYAe.geometry} material={nodes.aEQvkfzeWvwzYAe.material} />
          <mesh geometry={nodes.dwwWsLxRsdeWNuY.geometry} material={nodes.dwwWsLxRsdeWNuY.material} />
          <mesh geometry={nodes.uzbwArIObdMRDiX.geometry} material={nodes.uzbwArIObdMRDiX.material} />
          <mesh geometry={nodes.IKFNZjXnJPkRlsj.geometry} material={nodes.IKFNZjXnJPkRlsj.material} />
          <mesh geometry={nodes.sEZkXDXAzFzaCpi.geometry} material={materials.JAXIvIljFWpqimH} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/appleseris5.gltf')
